# Generated by Django 6.0.3 on 2026-03-21 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        ('dealerships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDriveBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Очікує підтвердження'), ('confirmed', 'Підтверджено'), ('cancelled', 'Скасовано')], default='pending', max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='cars.car')),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='dealerships.dealership')),
            ],
            options={
                'verbose_name': 'Запис на тест-драйв',
                'verbose_name_plural': 'Записи на тест-драйв',
                'ordering': ['-created_at'],
            },
        ),
    ]
