# Generated by Django 6.0.4 on 2026-04-25 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdrivebooking',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
