# Generated by Django 6.0.3 on 2026-03-21 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealerships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Марка',
                'verbose_name_plural': 'Марки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('body_type', models.CharField(choices=[('sedan', 'Седан'), ('hatchback', 'Хетчбек'), ('crossover', 'Кросовер'), ('suv', 'Позашляховик'), ('minivan', 'Мінівен'), ('coupe', 'Купе'), ('pickup', 'Пікап'), ('wagon', 'Універсал')], max_length=20)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('gas', 'Газ (LPG)'), ('hybrid', 'Гібрид'), ('electric', 'Електро')], max_length=10)),
                ('transmission', models.CharField(choices=[('manual', 'Механіка'), ('automatic', 'Автомат'), ('cvt', 'Варіатор'), ('robot', 'Робот')], max_length=10)),
                ('drive_type', models.CharField(choices=[('fwd', 'Передній'), ('rwd', 'Задній'), ('awd', 'Повний')], max_length=5)),
                ('condition', models.CharField(choices=[('new', 'Новий'), ('used', 'Вживаний')], max_length=5)),
                ('engine_volume', models.DecimalField(decimal_places=1, max_digits=3)),
                ('power_hp', models.PositiveSmallIntegerField()),
                ('mileage_km', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(max_length=50)),
                ('avg_fuel_consumption', models.DecimalField(decimal_places=1, help_text='Середнє споживання палива, л/100км', max_digits=4)),
                ('price_uah', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('available', 'В наявності'), ('reserved', 'Заброньовано'), ('sold', 'Продано')], default='available', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='dealerships.dealership')),
            ],
            options={
                'verbose_name': 'Автомобіль',
                'verbose_name_plural': 'Автомобілі',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/')),
                ('is_main', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.car')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='cars.brand')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Моделі',
                'ordering': ['name'],
                'unique_together': {('brand', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year_start', models.PositiveSmallIntegerField()),
                ('year_end', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='cars.carmodel')),
            ],
            options={
                'verbose_name': 'Покоління',
                'verbose_name_plural': 'Покоління',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='generation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.generation'),
        ),
    ]
