export const translations = {
  ua: {
    nav: { home: 'Головна', catalog: 'Каталог', salons: 'Салони', compare: 'Порівняння', search: 'Пошук автомобілів...', login: 'Увійти', logout: 'Вийти', profile: 'Профіль' },
    home: { hero_title: 'Знайди своє', hero_title2: 'Ідеальне Авто', hero_sub: 'Преміум автомобілі від надійних дилерів. Чи шукаєш ти потужність, розкіш або економність — ми тебе прикриємо.', brand: 'Марка', model: 'Модель', max_price: 'Макс. ціна', search_btn: 'Шукати авто', featured: 'Популярні авто', featured_sub: 'Наша підбірка преміум автомобілів', our_salons: 'Наші Салони', salons_sub: 'Відвідайте наші шоуруми та ознайомтесь з колекцією', view_details: 'Детальніше', view_all: 'Всі авто' },
    catalog: { title: 'Каталог авто', filters: 'Фільтри', brand: 'Марка', price_range: 'Діапазон цін', year: 'Рік', mileage: 'Пробіг', reset: 'Скинути фільтри', sort: 'Сортувати', sort_price_asc: 'Від найдешевших', sort_price_desc: 'Від найдорожчих', sort_year: 'Спочатку новіші', sort_mileage: 'З меншим пробігом', vehicles: 'авто доступно', new: 'Новий', used: 'Вживаний', view: 'Переглянути' },
    car: { specifications: 'Характеристики', engine: 'Двигун', power: 'Потужність', acceleration: 'Розгін 0-100', top_speed: 'Макс. швидкість', fuel_type: 'Тип пального', transmission: 'Трансмісія', drive_type: 'Привід', body_type: 'Тип кузова', year: 'Рік', mileage: 'Пробіг', seats: 'Місць', color: 'Колір', price: 'Ціна', book_test_drive: 'Записатись на тест-драйв', add_favorites: 'Додати в обране', remove_favorites: 'Прибрати з обраного', add_compare: 'Порівняти', available_at: 'В наявності у салоні', view_salon: 'Деталі салону', calculator: 'Калькулятор витрат', monthly_km: 'Місячний пробіг (км)', fuel_cost: 'Витрати на пальне', maintenance: 'Обслуговування', taxes: 'Податки', total_monthly: 'Всього на місяць', total_yearly: 'Всього на рік' },
    salons: { title: 'Наші Салони', sub: 'Відвідайте наші шоуруми та ознайомтесь з колекцією', available_cars: 'Доступних авто', manager: 'Менеджер', vehicles: 'авто' },
    compare: { title: 'Порівняння авто', sub: 'Порівняння обраних автомобілів', add_car: 'Додати авто', remove: 'Видалити', view_details: 'Детальніше', price: 'Ціна', year: 'Рік', condition: 'Стан', engine: 'Двигун', power: 'Потужність', acceleration: 'Розгін', top_speed: 'Макс. швидкість', fuel_type: 'Пальне', transmission: 'Трансмісія', drive_type: 'Привід', mileage: 'Пробіг', body_type: 'Кузов', empty: 'Немає авто для порівняння', empty_sub: 'Перейдіть до каталогу і натисніть "Порівняти" на будь-якому авто', go_catalog: 'До каталогу', different: 'різні' },
    profile: { title: 'Мій Профіль', sub: 'Керуй акаунтом та налаштуваннями', favorites: 'Обране', test_drives: 'Тест-драйви', recently_viewed: 'Нещодавно переглянуті', settings: 'Налаштування', favorite_cars: 'Улюблені авто', no_favorites: 'Немає обраних авто', no_favorites_sub: 'Переглядай каталог і додавай авто в обране', test_drive_requests: 'Запити на тест-драйв', no_requests: 'Немає запитів на тест-драйв', recently_viewed_cars: 'Нещодавно переглянуті авто', no_viewed: 'Немає переглянутих авто', profile_settings: 'Налаштування профілю', full_name: 'Повне ім\'я', email: 'Електронна пошта', phone: 'Телефон', change_password: 'Змінити пароль', current_password: 'Поточний пароль', new_password: 'Новий пароль', confirm_password: 'Підтвердити пароль', save: 'Зберегти зміни', update_password: 'Оновити пароль', confirmed: 'Підтверджено', pending: 'Очікує', cancelled: 'Скасовано', view_car: 'Переглянути авто', cancel: 'Скасувати' },
    auth: { login_title: 'З поверненням', login_sub: 'Увійдіть до свого акаунту AutoHub', email: 'Електронна пошта', password: 'Пароль', forgot_password: 'Забули пароль?', sign_in: 'Увійти', or_continue: 'Або продовжити через', google: 'Увійти через Google', no_account: 'Немає акаунту?', sign_up: 'Зареєструватись', register_title: 'Створити акаунт', register_sub: 'Зареєструйтесь в AutoHub', username: 'Ім\'я користувача', confirm_password: 'Підтвердити пароль', phone: 'Телефон', create_account: 'Створити акаунт', have_account: 'Вже є акаунт?', sign_in_link: 'Увійти' },
    booking: { title: 'Записатись на тест-драйв', car: 'Автомобіль', salon: 'Салон', date_time: 'Дата та час', comment: 'Коментар (необов\'язково)', comment_placeholder: 'Додаткові побажання...', submit: 'Підтвердити запис', cancel: 'Скасувати', success: 'Запис успішно створено!', login_required: 'Для запису необхідно увійти в акаунт' },
    footer: { about: 'Про AutoHub', about_text: 'Ваш надійний партнер у пошуку ідеального авто. Маємо декілька локацій та різноманітний асортимент.', quick_links: 'Швидкі посилання', browse: 'Переглянути каталог', showrooms: 'Наші шоуруми', compare: 'Порівняти авто', account: 'Мій акаунт', contact: 'Контакти', follow: 'Ми в соцмережах', rights: 'Всі права захищені' },
  },
  en: {
    nav: { home: 'Home', catalog: 'Catalog', salons: 'Salons', compare: 'Compare', search: 'Search cars...', login: 'Sign In', logout: 'Sign Out', profile: 'Profile' },
    home: { hero_title: 'Find Your', hero_title2: 'Perfect Ride', hero_sub: 'Premium vehicles from trusted dealers. Whether you\'re looking for performance, luxury, or efficiency, we\'ve got you covered.', brand: 'Brand', model: 'Model', max_price: 'Max Price', search_btn: 'Search Cars', featured: 'Featured Cars', featured_sub: 'Discover our handpicked selection of premium vehicles', our_salons: 'Our Salons', salons_sub: 'Visit our showrooms and discover our collection in person', view_details: 'View Details', view_all: 'View All' },
    catalog: { title: 'Car Catalog', filters: 'Filters', brand: 'Brand', price_range: 'Price Range', year: 'Year', mileage: 'Mileage', reset: 'Reset Filters', sort: 'Sort by', sort_price_asc: 'Cheapest first', sort_price_desc: 'Most expensive first', sort_year: 'Newest first', sort_mileage: 'Lowest mileage', vehicles: 'vehicles available', new: 'New', used: 'Used', view: 'View' },
    car: { specifications: 'Full Specifications', engine: 'Engine', power: 'Power', acceleration: 'Acceleration', top_speed: 'Top Speed', fuel_type: 'Fuel Type', transmission: 'Transmission', drive_type: 'Drive Type', body_type: 'Body Type', year: 'Year', mileage: 'Mileage', seats: 'Seats', color: 'Color', price: 'Price', book_test_drive: 'Book Test Drive', add_favorites: 'Add to Favorites', remove_favorites: 'Remove from Favorites', add_compare: 'Add to Compare', available_at: 'Available at', view_salon: 'View Salon Details', calculator: 'Cost Calculator', monthly_km: 'Monthly Mileage (km)', fuel_cost: 'Fuel Cost', maintenance: 'Maintenance', taxes: 'Taxes', total_monthly: 'Total Monthly Cost', total_yearly: 'Total Yearly Cost' },
    salons: { title: 'Our Salons', sub: 'Visit our showrooms and discover our collection in person', available_cars: 'Available Cars', manager: 'Manager', vehicles: 'vehicles' },
    compare: { title: 'Compare Cars', sub: 'Side-by-side comparison of selected vehicles', add_car: 'Add Car', remove: 'Remove', view_details: 'View Details', price: 'Price', year: 'Year', condition: 'Condition', engine: 'Engine', power: 'Power', acceleration: 'Acceleration', top_speed: 'Top Speed', fuel_type: 'Fuel Type', transmission: 'Transmission', drive_type: 'Drive Type', mileage: 'Mileage', body_type: 'Body Type', empty: 'No cars to compare', empty_sub: 'Go to catalog and click "Compare" on any car', go_catalog: 'Browse Catalog', different: 'different' },
    profile: { title: 'My Profile', sub: 'Manage your account and preferences', favorites: 'Favorites', test_drives: 'Test Drives', recently_viewed: 'Recently Viewed', settings: 'Settings', favorite_cars: 'Favorite Cars', no_favorites: 'No favorite cars yet', no_favorites_sub: 'Browse the catalog and add cars to favorites', test_drive_requests: 'Test Drive Requests', no_requests: 'No test drive requests yet', recently_viewed_cars: 'Recently Viewed Cars', no_viewed: 'No recently viewed cars', profile_settings: 'Profile Settings', full_name: 'Full Name', email: 'Email', phone: 'Phone', change_password: 'Change Password', current_password: 'Current Password', new_password: 'New Password', confirm_password: 'Confirm Password', save: 'Save Changes', update_password: 'Update Password', confirmed: 'Confirmed', pending: 'Pending', cancelled: 'Cancelled', view_car: 'View Car', cancel: 'Cancel' },
    auth: { login_title: 'Welcome Back', login_sub: 'Sign in to your AutoHub account', email: 'Email', password: 'Password', forgot_password: 'Forgot password?', sign_in: 'Sign In', or_continue: 'Or continue with', google: 'Sign in with Google', no_account: "Don't have an account?", sign_up: 'Sign up', register_title: 'Create Account', register_sub: 'Join AutoHub today', username: 'Username', confirm_password: 'Confirm Password', phone: 'Phone', create_account: 'Create Account', have_account: 'Already have an account?', sign_in_link: 'Sign in' },
    booking: { title: 'Book a Test Drive', car: 'Car', salon: 'Salon', date_time: 'Date & Time', comment: 'Comment (optional)', comment_placeholder: 'Any additional requests...', submit: 'Confirm Booking', cancel: 'Cancel', success: 'Booking created successfully!', login_required: 'Please sign in to book a test drive' },
    footer: { about: 'About AutoHub', about_text: "We're your trusted partner in finding the perfect vehicle. With multiple locations and a diverse inventory, we make car buying simple.", quick_links: 'Quick Links', browse: 'Browse Inventory', showrooms: 'Visit Our Showrooms', compare: 'Compare Vehicles', account: 'My Account', contact: 'Get in Touch', follow: 'Follow Us', rights: 'All rights reserved' },
  }
};
